### PR TITLE
Add rule_id to vulnerability object

### PR DESCRIPTION
**Pull request by anthturner**
# What I did
Added `rule_id` field to JSON generated from Vulnerability object. I also added this back to Swagger since it would be there in the export

# How to verify it
Export to JSON and look at the vulnerability structure

# Description for the changelog
Added rule_id to Vulnerability JSON

### CODE REVIEW

**Review by matheusalcantarazup — CHANGES_REQUESTED** [review]
Please, follow the [Contributing](https://github.com/ZupIT/horusec/blob/main/CONTRIBUTING.md#developer-certificate-of-origin---dco) guide to add Developer Certificate of Origin.

Since you make two commit, you can squash them and them add a single DCO.

**Comment by anthturner** [comment]
> Please, follow the [Contributing](https://github.com/ZupIT/horusec/blob/main/CONTRIBUTING.md#developer-certificate-of-origin---dco) guide to add Developer Certificate of Origin.
> 
> Since you make two commit, you can squash them and them add a single DCO.

Done, thanks.

**Comment by anthturner** [comment]
Sorry, interpreted that as signed as in gpg. Fixed.

**Review by matheusalcantarazup — APPROVED** [review]

**Review by nathanmartinszup — APPROVED** [review]

**Comment by matheusalcantarazup** [comment]
Thanks for your contribution @anthturner

**Pull request merged**
